## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [7]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [72]:
# Type your solution here
import pandas as pd
import numpy as np

# Q1-1
frame = pd.DataFrame(data)
# print(frame)

# Q1-2
frame[((frame["job"] == "psychologist") & (frame["num_cars"] > frame["family_size"])) | ((frame["job"] == "teacher") & (frame["num_cars"] > frame["family_size"]))]

# Q1-3
frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)] 

# Q1-4
uniqueJobs = frame.job.unique()
print("number of unique jobs:", uniqueJobs.size)


number of unique jobs: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [104]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [105]:
# Type your solution here
df = pd.concat([fruit, weights], axis = 1)
# print(df)

df.groupby(0).mean()
print("mean of weights of each fruit: ")
weights.groupby(fruit).mean()

mean of weights of each fruit: 


apple     3.5
banana    5.5
carrot    7.5
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [34]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [74]:
# Type your solution here

# Q3-1
sortedI = np.argsort(course_name)
print("indices of sorted elements:", sortedI)

# Q3-2
p = np.char.startswith(course_name, "P")
print("if course name starts with 'P':", p)

indices of sorted elements: [1 3 0 2 4]
if course name starts with 'P': [ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [38]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [75]:
# Type your solution here

# Q4-1
print("original:", student_id)
reversed = student_id[::-1]
print("reversed:", reversed)

# Q4-2
sorted = np.sort(student_id)
# print(sorted)

largest = sorted[-3:]
print("three largest values:", largest)

original: [1023 1671 1682 4532 5202 5241 6230]
reversed: [6230 5241 5202 4532 1682 1671 1023]
three largest values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [92]:
# Type your solution here

# Hint: you can use arange to start off

num = np.arange(1, 100)
multiples = num[(num % 3 == 0) | (num % 5 == 0)]
sum = multiples.sum()
print("sum of multiples of 3 or 5 below 100:", sum)

sum of multiples of 3 or 5 below 100: 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [87]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [88]:
# Type your solution here

# Q6-1
arr[:, [1,2]] = arr[:, [2,1]]
print("after swapping column 1 and column 2:")
print(arr)

# Q6-2
arr[[0,1], :] = arr[[1,0], :]
print("after swapping row 0 and row 1:")
print(arr)

after swapping row 0 and row 1:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
